import Footer from "./LayoutComponents/Footer/Footer";
import Navbar from "./LayoutComponents/Navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <>
          <Navbar />
          {children}
          <Footer />
        </>
      </body>
    </html>
  );
}
